[package]
name = "test_lock"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shmem = { path = "../shmem" }
uname = "0.1.1"
getopts = "0.2"
clap = "3.1"
